# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 275d9d9a14ba81c97e616fa5aad35f15c4b9a68c396ac8f7e374952c0da729f88ece4f7a2633ea2bbc617122da1c0a029915a35b275573ba5c7f3ce10cdb6f4e

test:
  secret_key_base: 94c80e43577ef4514c5fd5a917e19b99c3f74e7886772232ec248075f0733513c66eca3e4949936aff7c7df5cb2c3deaf1910221a72d470fb7073c04c55ffc4f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
